Data Cube Documentation ✨
Open-EO/openeo.org pull request #31
Opened 2021-03-11 13:44 UTC by m-mohr

2021-03-11 13:45 UTC, m-mohr commented on documentation/1.0/datacubes.md
> + ### Processes on Dimensions
Throughout the document many lines start with a space character. That should be fixed. @jonathom

2021-03-11 15:15 UTC, m-mohr commented on documentation/1.0/datacubes.md
> + ### Processes on Dimensions
Fixed

2021-03-11 15:17 UTC, m-mohr commented
Make sure to pull my latest changes to not run into merge conflicts @jonathom

2021-03-11 17:34 UTC, m-mohr commented
Note to myself: Squash and merge to make history of images lighter

2021-03-11 19:53 UTC, jonathom commented
ready for review

2021-03-11 21:27 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +TODOs / Questions:
Remove the ToDos @jonathom  ;-)

2021-03-11 22:02 UTC, jonathom commented on documentation/1.0/datacubes.md
> +TODOs / Questions:
done [x]

2021-03-17 14:31 UTC, christophfriedrich requested changes
I like it overall -- solid explanations and very nice graphics! See the comments for specific feedback.

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +When filtering data, only the data within the filter interval is returned. That can be a time interval, coordinates or specific bands. The datacube is then smaller, according to the selected data.
```suggestion
When filtering data, only the data that satisfies a condition is returned. For example, this condition could be a timestamp or interval, (a set of) coordinates, or specific bands. By applying filtering the datacube becomes smaller, according to the selected data.
```
- The filtering condition is not necessarily an interval
- The list of what that filtering condition could be is incomplete, hence "For example"
- I expanded the examples to showcase the multitude of possibilities (feel free to change them as you like)

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +In the image, the example datacube can be seen at the top with labeled dimensions. The filtering techniques are displayed separately below. First, the Datacube is filtered temporally with the interva
```suggestion
In the image, the example datacube can be seen at the top with labeled dimensions. The filtering techniques are displayed separately below. On the left, the datacube is filtered temporally with the interval `["2020-10-15", "2020-10-27"]`. The result is a cube with only the rasters for the timestep that lies within that interval (`"2020-10-25"`) and unchanged bands and spatial dimensions. Likewise, the original cube is filtered for a specific band `["nir"]` in the middle and a specific spatial region `[Polygon(...)]` on the right.
```
The different filterings here are not applied one after the other, but all to the same data, so I changed the words that would have indicated a step-by-step process.

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <img src="./datacubes/dc_filter.png" alt="Datacube timeseries">
```suggestion
    <img src="./datacubes/dc_filter.png" alt="Datacube filtering">
```

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +The `apply*()` functions employs a process on the datacube that calculates new pixel values for each pixel, based on `n` other pixels.
```suggestion
The `apply()` function employs a process on the datacube that calculates new pixel values for each pixel, based on `n` other pixels.
```
Or does that asterisk have a meaning?? If so, please explain.

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <img src="./datacubes/dc_apply_unary.png" alt="Datacube timeseries">
```suggestion
    <img src="./datacubes/dc_apply_unary.png" alt="Datacube apply unary">
```

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <img src="./datacubes/dc_apply_kernel.png" alt="Datacube timeseries">
```suggestion
    <img src="./datacubes/dc_apply_kernel.png" alt="Datacube apply spatial kernel">
```

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
Can there be other dimensions too except the 4 that are named here?

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <img src="./datacubes/dc_apply_ts.png" alt="Datacube timeseries">
```suggestion
    <img src="./datacubes/dc_apply_ts.png" alt="Datacube apply temporal moving average">
```

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <figcaption>Applying a moving average (temporal smoothing) by avegraging the direct temporal neighbourhoods of pixels. No padding is used, which leads to edge effects.</figcaption>
```suggestion
    <figcaption>Applying a moving average (temporal smoothing) by averaging the direct temporal neighbourhoods of pixels. No padding is used, which leads to edge effects.</figcaption>
```
typo

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +If `n` is larger than 1, the function is called n-ary. In practice, this means that the pixel neighbourhood is taken into account to calculate the new pixel value. Such neighbourhoods can be of tempo
This sounds a bit like "smoothing" is only possible for temporal, but of course it can just as well be applied spatially. In general I don't really like that the different types of dimensions are described differently in this paragraph -- isn't the temporal example in fact also just a "kernel"? I thought it's the very point of datacubes that dimensions can be treated all the same.

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +In a resampling process, the _layout_ of a certain dimension is changed into another _layout_, most likely also changing the resolution of that dimension. This is done by mapping values of the source
```suggestion
In a resampling process, the _layout_ of a certain dimension is changed into another _layout_, most likely also changing the resolution of that dimension. This is done by mapping values of the source (old) datacube to the new layout of the target (new) datacube. During that process, resolutions can be _upscaled_ or _downscaled_ (also called _upsampling_ and _downsampling_), depending on whether they have a finer or a coarser spacing afterwards. During that process, a function is needed to translate the existing data into the new resolution. A prominent example is to reproject a datacube into the coordinate reference system of another datacube, for example in order to merge the two cubes.
```
easier to understand

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <img src="./datacubes/dc_resample_time.png" alt="Datacube timeseries">
```suggestion
    <img src="./datacubes/dc_resample_time.png" alt="Datacube temporal resampling (up and down)">
```

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <figcaption>Temporal downscaling is seen on the left, upscaling on the right. The temporal layout that the cubes are resampled to is displayed in the middle.</figcaption>
```suggestion
    <figcaption>Temporal downsampling is seen on the left, upsampling on the right. The temporal layout that the cubes are resampled to is displayed in the middle.</figcaption>
```
Stick to one of the terms. Especially don't use a different one in the caption than in the actual graphic.

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +The second figure displays spatial resampling. Common resampling methods are "near" and "bilinear". Observe how in the upsampling process, the output datacube has not gained in information value. The
```suggestion
The second figure showcases spatial resampling. Common resampling methods are "nearest neighbour" and "bilinear interpolation". Note that in the upsampling process, the output datacube has not gained in information value. The resulting grid still carries the same pixel information, but in higher spatial resolution.
```
I think those are the ones you meant? Anyway, I think it would be very good to describe them at least in somewhat more detail!

What is described in the second sentence can't really be "observed" that good in the figure... It's up to you whether you want to change the text or the figure ;)

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <img src="./datacubes/dc_resample_space.png" alt="Datacube timeseries">
```suggestion
    <img src="./datacubes/dc_resample_space.png" alt="Datacube spatial resampling (up and down)">
```

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +The `reduce_dimension*()` process _collapses_ a whole dimension of the datacube. It does so by using some sort of **reducer**, which is a function that calculates a single result from an amount of va
```suggestion
The `reduce_dimension()` process _collapses_ a whole dimension of the datacube. It does so by using some sort of **reducer**, which is a function that calculates a single result from an amount of values, as e.g. `mean()`, `min()` and `max()` are. For example we can reduce the time dimension of a time series by calculating the mean value over all timesteps for each pixel. We are left with a cube that has no time dimension, because all values of that dimension are compressed into a single mean value. The same goes for e.g. the spatial dimensions: If we calculate the mean along the x and y dimensions, we are left without any spatial dimensions, but a mean value for each instance that previously was a raster is returned. In the image below, the dimensions that are reduced are crossed out in the result.
```
Same question with the asterisk again?

Word order, correct proposition, clarity

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +Think of it as a waste press that does math instead of using brute force. Given a representation of our example data cube, let's see how it is affected.
```suggestion
Think of it as a waste press that does math instead of using brute force. Given a representation of our example datacube, let's see how it is affected.
```
The *only* occurrence in this text where this word is spelled *with* the space.

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +Think of it as a waste press that does math instead of using brute force. Given a representation of our example data cube, let's see how it is affected.
Doesn't a waste press squash in all directions, not just one? That would render this analogy (that I like in general) somewhat misleading :(

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <img src="./datacubes/dc_reduce.png" alt="Datacube timeseries">
```suggestion
    <img src="./datacubes/dc_reduce.png" alt="Datacube reduce">
```

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +A spatial agregation works in a similar manner. Polygons, lines and points can be selected for grouping. Their spatial dimension is then reduced by a given process and thus, a vector cube is returned
Again, maybe this is better suited in a dedicated "vector cubes" section?

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <img src="./datacubes/dc_aggregate_space.png" alt="Datacube timeseries">
```suggestion
    <img src="./datacubes/dc_aggregate_space.png" alt="Datacube spatial aggregation">
```

2021-03-17 14:31 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +While the layout of the reduced dimension is changed, other dimensions keep their resolution and geometry.
```suggestion
While the layout of the reduced dimension is changed, other dimensions keep their resolution and geometry. But in contrast to pure `reduce`, the dimension along which `aggregate` is performed still exists after the operation.
```
Maybe that helps clarifying things?

2021-03-17 14:33 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
In the text the temporal dimension is called `t`, in the table and the graphics `time`.

2021-03-17 14:48 UTC, christophfriedrich commented
Suggestions regarding the graphics:
- `apply_unary`: In the text the function is called `abs()`, in the graphic `absolute()`
- `resample_space`: With this perspective, the resampling is hardly visible. Is it possible to "turn" the rendering ("into the screen plane" if you get what I mean?) to get more of a top view? Or maybe even better: Don't use the timeseries representation, but the flat one?
- `resample_time`: Why is there no data for 2020-09-28?
- `reduce`: For the example in the middle, could you move the "time" dimension name closer to the rendering?

2021-03-17 14:51 UTC, jonathom commented on documentation/1.0/datacubes.md
> +Datacubes are multidimensional arrays with one or more spatial or temporal dimension(s). They are the way in which data is represented in OpenEO. They provide a nice and tidy interface for spatiotemp
I used "you" and "we" on purpose, also discussed this with Matthias. The vector cubes however can definitely be moved to their own section, especially as there isn't much to do with them yet anyway - good idea!

2021-03-17 14:51 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +In a resampling process, the _layout_ of a certain dimension is changed into another _layout_, most likely also changing the resolution of that dimension. This is done by mapping values of the source
Merging two cubes is a concept that is new here -- does mentioning it help in understanding or does it lead to confusion? Should it be explained in more detail, possibly in a separate section? (open questions)

2021-03-17 14:53 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +The resolution of a dimension gives information about what interval lies between observations. This is most obvious with the temporal resolution, where the intervals depict how often obervations were
Is "spectral resolution" correctly explained with "how many bands you have"??

2021-03-17 14:53 UTC, jonathom commented on documentation/1.0/datacubes.md
> +    <figcaption>An example datacube with x, y, bands and time dimension.</figcaption>
I thought it's better to highlight parameters, to make clear they are somewhat special to the example, but to not highlight dim names as they are a convention and therefore a normal part of the text. other thoughts @m-mohr @edzer ?

2021-03-17 14:54 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +Datacubes are multidimensional arrays with one or more spatial or temporal dimension(s). They are the way in which data is represented in OpenEO. They provide a nice and tidy interface for spatiotemp
In the text it's called "near-infrared", everywhere else "nir" -- I guess that's okay.

2021-03-17 14:58 UTC, jonathom commented on documentation/1.0/datacubes.md
> +There are multiple properties stored for each dimension:
That I don't know. @m-mohr ?

2021-03-17 15:01 UTC, jonathom commented on documentation/1.0/datacubes.md
> +Some processes are typically applied "along a dimension". You can imagine said dimension as an arrow and whatever is happening as a parallel process to that arrow. It simply means: "we focus on _this
yup I was afraid it wouldn't. I made a note and will take it out.

2021-03-17 15:06 UTC, jonathom commented on documentation/1.0/datacubes.md
> +When filtering data, only the data within the filter interval is returned. That can be a time interval, coordinates or specific bands. The datacube is then smaller, according to the selected data.
no need to change, I like the examples as you suggested.

2021-03-17 15:09 UTC, jonathom commented on documentation/1.0/datacubes.md
> +In the image, the example datacube can be seen at the top with labeled dimensions. The filtering techniques are displayed separately below. First, the Datacube is filtered temporally with the interva
Yes, good note.

2021-03-17 15:13 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The `apply*()` functions employs a process on the datacube that calculates new pixel values for each pixel, based on `n` other pixels.
Well there are `apply`, `apply_dimension`, `apply_kernel` and `apply_neighbourhood`. I adopted this from current datacube doc, I like it.

2021-03-17 15:23 UTC, jonathom commented on documentation/1.0/datacubes.md
> +Datacubes are multidimensional arrays with one or more spatial or temporal dimension(s). They are the way in which data is represented in OpenEO. They provide a nice and tidy interface for spatiotemp
It's meant to spell out that abbreviation at the first mention. I believe people will make that connection :)

2021-03-17 15:26 UTC, edzer commented
Still need to do my review, but at first glance this looks REALLY, REALLY good!! Worth looking (and commenting?): @mkadunc @jdries @aljacob @przell

2021-03-17 15:36 UTC, jonathom commented on documentation/1.0/datacubes.md
> +If `n` is larger than 1, the function is called n-ary. In practice, this means that the pixel neighbourhood is taken into account to calculate the new pixel value. Such neighbourhoods can be of tempo
Tricky. I tried here to make things that are clear to me and you a bit more understandable for people that have never done any of this. And I think from that perspective it's easier to look at the difference. The spatial kernel apply is called `apply_kernel`, vs e.g. `apply_neighbourhood` that can be used for temporal apply. I think the subtleties can wait.

The `(e.g. smoothing)` was added because I think it's harder to understand a temporal neighbourhood than a spatial neighbourhood (more natural use of "neighbourhood"), for people to get an idea of what could be done here. We can take it out if that is a source of confusion.

2021-03-17 15:43 UTC, m-mohr commented on .vuepress/config.js
> +        {text: 'Data Cubes', link: 'datacubes.html'},
Indeed:

```suggestion
        {text: 'Datacubes', link: 'datacubes.html'},
```

2021-03-17 15:44 UTC, m-mohr commented on .vuepress/theme/styles/index.styl
> +  figure
Yes, this is optimized for the website.

2021-03-17 15:47 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +    <figcaption>An example datacube with x, y, bands and time dimension.</figcaption>
I have no strong preference, both options are good to understand.

2021-03-17 15:48 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
Yes, I agree.

2021-03-17 15:48 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The second figure displays spatial resampling. Common resampling methods are "near" and "bilinear". Observe how in the upsampling process, the output datacube has not gained in information value. The
You are right, the example methods can go. Or I could only mention "nearest neighbour" and explain further. 
> can't really be "observed" that good in the figure

Yup that's simply a "space in the graphic" issue. I hope it's visible when zooming in.

2021-03-17 15:51 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +There are multiple properties stored for each dimension:
No, for example, bands don't have their own reference system, which is stored only for spatial and temporal dimensions.
It's an implementation detail though. We could write something like:

```suggestion
The following properties are usually available for dimensions:
```

2021-03-17 15:52 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +* type
pre-defined types: spatial, temporal, bands, other - Including it in the table would result in the following (pretty obvious) mapping:

- x + y => spatial
- t => temporal
- bands => bands

2021-03-17 15:56 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The `reduce_dimension*()` process _collapses_ a whole dimension of the datacube. It does so by using some sort of **reducer**, which is a function that calculates a single result from an amount of va
Additionally there is `reduce_dimension_binary()`.
thanks for grammar correction, one comment: I wrote "out of all timesteps" because the meaning of "_over_ all timesteps" is something I learned along the way and didn't know from the start. Maybe "... mean of all timesteps" works?

2021-03-17 15:57 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +The `apply*()` functions employs a process on the datacube that calculates new pixel values for each pixel, based on `n` other pixels.
Maybe we could change to 

```suggestion
The `apply*` functions (e.g. `apply`, `apply_dimension` and `apply_kernel`) employ a process on the datacube that calculates new pixel values for each pixel, based on `n` other pixels.
```

We could also link the process names to processes.openeo.org, e.g.

```
`[apply](https://processes.openeo.org/#apply)`
```

2021-03-17 16:02 UTC, jonathom commented on documentation/1.0/datacubes.md
> +A spatial agregation works in a similar manner. Polygons, lines and points can be selected for grouping. Their spatial dimension is then reduced by a given process and thus, a vector cube is returned
I think it's important to understand what the spatial aggregation does. And as a vector cube is returned, I think it's wrong to not mention this here.

2021-03-17 16:04 UTC, jonathom commented on documentation/1.0/datacubes.md
> +While the layout of the reduced dimension is changed, other dimensions keep their resolution and geometry.
idk. for me, "the layout ... is changed" implies this.

2021-03-17 16:06 UTC, jonathom commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
I think for the table, consistency makes sense (noted, will change) but not for graphics, which I hope could partly stand for themselves.

2021-03-17 16:06 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +While the layout of the reduced dimension is changed, other dimensions keep their resolution and geometry.
We can just add it in, it may improve things but certainly doesn't make things worse. ;-)

2021-03-17 16:10 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +The second figure displays spatial resampling. Common resampling methods are "near" and "bilinear". Observe how in the upsampling process, the output datacube has not gained in information value. The
Images will also be a bit larger on the website, I think.

2021-03-17 16:18 UTC, jonathom commented on documentation/1.0/datacubes.md
> +While the layout of the reduced dimension is changed, other dimensions keep their resolution and geometry.
agreed.

2021-03-17 16:28 UTC, jonathom commented on documentation/1.0/datacubes.md
> +It is important to understand that datacubes are designed to make things easier for us, and are not literally a cube, meaning that the above plot is just as good a way to represent the dimensionality
```suggestion
It is important to understand that datacubes are designed to make things easier for us, and are not literally a cube, meaning that the above plot is just as good a representation as any other. That is why we can switch the dimensions around and display them in whatever way we want, including the view below (dimension labels are shown):
```

How about this? because the plot above this "flat" one is actually mixing names and labels, it wasn't even a useful sentence. So now the hint that these are the labels suffices.

2021-03-17 18:33 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The second figure displays spatial resampling. Common resampling methods are "near" and "bilinear". Observe how in the upsampling process, the output datacube has not gained in information value. The
```suggestion
The second figure displays spatial resampling. Observe how in the upsampling process, the output datacube has not gained in information value. The resulting grid still carries the same pixel information, but in higher spatial resolution.
```
I would like to leave it "Observe", so people go look at it instead of accepting it.

2021-03-18 12:00 UTC, jonathom commented on documentation/1.0/datacubes.md
> +Datacubes are multidimensional arrays with one or more spatial or temporal dimension(s). They are the way in which data is represented in OpenEO. They provide a nice and tidy interface for spatiotemp
resolved with new commit. The explanation of vector cubes is withheld for a more detailed chapter to follow.

2021-03-18 12:03 UTC, jonathom commented on documentation/1.0/datacubes.md
> +## Functions on Datacubes
The chapter is now called "Applying Processes on Dimensions".

2021-03-18 12:04 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The `apply*()` functions employs a process on the datacube that calculates new pixel values for each pixel, based on `n` other pixels.
I added links to the functions for all chapters.

2021-03-18 12:06 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The second figure displays spatial resampling. Common resampling methods are "near" and "bilinear". Observe how in the upsampling process, the output datacube has not gained in information value. The
updated with new commit

2021-03-18 12:13 UTC, jonathom commented on documentation/1.0/datacubes.md
> +In a resampling process, the _layout_ of a certain dimension is changed into another _layout_, most likely also changing the resolution of that dimension. This is done by mapping values of the source
It is indeed but I think it gives an example for _why_ one would want to resample. I wouldn't open a section on it, as it's not a core datacube process. if other ppl think it's confusing we can remove

2021-03-18 12:59 UTC, jonathom commented
Thank you for your review @christophfriedrich! To answer your comment:
> apply_unary: In the text the function is called abs(), in the graphic absolute()

Changed it to absolute().
> resample_space: With this perspective, the resampling is hardly visible. Is it possible to "turn" the rendering ("into the screen plane" if you get what I mean?) to get more of a top view? Or maybe even better: Don't use the timeseries representation, but the flat one?

It would be possible to turn the cube, but would mess up the consistency throughout the plots. I'm not sure if flat plots would make a difference in available space here. @m-mohr also proposed to split the graphics for the two processes. I could also make them all just _bigger_ (also messing with consistency), something in the likes of this [(old version for reference)](https://github.com/Open-EO/openeo.org/blob/datacube_doc/documentation/1.0/datacubes/dc_resample_space.png):
![exp_resample_space_new](https://user-images.githubusercontent.com/45635480/111628105-20f8a900-87f0-11eb-8ef5-ac6b47dc5cec.png)
> resample_time: Why is there no data for 2020-09-28?

Whether there is data for previous time steps is dependent on the used resampling function. We thought it's more intuitive to not have data there.
> reduce: For the example in the middle, could you move the "time" dimension name closer to the rendering?

Yes I could, but I also considered consistency here, and also to show the original extent, to emphasize the reducing thats taking place.

Also, I liked the idea of adding process examples with links and went ahead and did it. Apart from that, I think another important point coming from your suggestions is whether or not dimension _names_ should also be code-highlighted. I only highlighted dimension labels before, also to make a difference between concrete values and conventional dim names. More opinions on this are appreciated.:)

2021-03-18 15:22 UTC, christophfriedrich commented
> It would be possible to turn the cube, but would mess up the consistency throughout the plots.

Valid point, but IMO that wouldn't be overly bad, the gain is worth it.

> I'm not sure if flat plots would make a difference in available space here.

It would certainly make a difference! Mainly because it would remove the perspective. A 400x400 px square shows more than a 100x300px skewed ~rectangle~ quadrangle...

> @m-mohr also proposed to split the graphics for the two processes.

I don't get what exactly you mean. One graphic each for down- and upsampling?

> I could also make them all just _bigger_ (also messing with consistency)

I like your example, this definitely improves things, and I think the consistency issue here is even more negligible than above. Still, I guess I'd prefer the flat view. If you want to show something spatial in detail, the timeseries-oriented representation just isn't so useful.

---

> Whether there is data for previous time steps is dependent on the used resampling function. We thought it's more intuitive to not have data there.

It wasn't for me :D 2020-09-28 is closer to the existing data point 2020-10-01 than 2020-10-06, so nearest neighbour should yield a result here too. If it was bilinear interpolation, there shouldn't be data for 2020-10-30 either :thinking: I'd prefer data for the first point too, or alternatively, add a note to the figcaption.

> > reduce: For the example in the middle, could you move the "time" dimension name closer to the rendering?
> 
> Yes I could, but I also considered consistency here, and also to show the original extent, to emphasize the reducing thats taking place.

Valid point. Maybe add a small grey border around each result then?

> whether or not dimension _names_ should also be code-highlighted. I only highlighted dimension labels before, also to make a difference between concrete values and conventional dim names. More opinions on this are appreciated.:)

I would highlight them in some way. Maybe keep code-highlighting for labels and put names in italics?

But then again, function names are code-highlighted too...

2021-03-18 15:25 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +    <figcaption>An example datacube with x, y, bands and time dimension.</figcaption>
Regardless of whether we highlight it or not (I can live with either way), I think the "4 dimensions: [list]" adds clarity, but that's just a minor detail.

2021-03-18 15:30 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +It is important to understand that datacubes are designed to make things easier for us, and are not literally a cube, meaning that the above plot is just as good a way to represent the dimensionality
> the plot above this "flat" one is actually mixing names and labels

I didn't even notice that yet :sweat_smile: 

:arrow_right: Is this hint even necessary? Maybe move it to the figure's caption.

2021-03-18 15:40 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +* type
Thanks. "Pre-defined" according to the openEO API spec I guess? I agree that's quite obvious then, but only when you know that it's these values that are possible. I'd include them in the table nonetheless.

2021-03-18 15:42 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +* type
Don't know what to do about "other". Maybe simply:

```suggestion
* type (spatial/temporal/bands/other)
```

2021-03-18 15:56 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +## Functions on Datacubes
I'm just cautious to use consistent terminology whenever possible. Mainly to avoid confusion.

The [glossary](https://openeo.org/documentation/1.0/glossary.html#processes) says:
> A process is an operation that performs a specific task on a set of parameters and returns a result. An example is computing a statistical operation, such as mean or median, on selected EO data. A process is **similar** to a function or method in programming languages.

(emphasis mine; I think this was written by @edzer)

> The chapter is now called "Applying Processes on Dimensions".

You meant "Processes on Datacubes" but yeah, I think that's better, so we at least don't have the two different words right after each other :+1:

2021-03-18 16:13 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
Then that should somehow be reflected in the text. The current wording ("there are", "there is", especially together with "furthermore") could be interpreted as "These are the ones that exist, no more".

2021-03-18 16:27 UTC, m-mohr commented on documentation/1.0/datacubes.md
> +* type
Yes, they are pre-defined by the API.

2021-03-18 16:57 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +If `n` is larger than 1, the function is called n-ary. In practice, this means that the pixel neighbourhood is taken into account to calculate the new pixel value. Such neighbourhoods can be of tempo
To me that raises the question why there are two different openEO processes for this at all, but that's not the point here :upside_down_face: 

Hm, I thought about it a bit and have come to the conclusion "yeah, better leave it out".

But actually having an example is good, so maybe:

> A temporal function works on a time series at a certain pixel location (e.g. smoothing values over time), a spatial function works on a kernel that weights the surrounding pixels (e.g. smoothing values with nearby observations).

2021-03-18 17:07 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +The second figure displays spatial resampling. Common resampling methods are "near" and "bilinear". Observe how in the upsampling process, the output datacube has not gained in information value. The
> I would like to leave it "Observe", so people go look at it instead of accepting it.

Good point, I like that! :+1: 

This "space in the graphic issue" would be solved when using the flat representation as suggested in [the other comment](https://github.com/Open-EO/openeo.org/pull/31#issuecomment-802016385).

> You are right, the example methods can go.

No :open_mouth: I'd at least name them, so readers get a clue what to google if they ask themselves "how the heck is that supposed to work" since _adding_ information sounds weird at first.

> Or I could only mention "nearest neighbour" and explain further.

Better, but I'd still list both. I understand that explaining bilinear interpolation is a bit over the top though. So TBH I'd settle for what I suggested above: Just name both and if anyone wants to know the details, they can consult the search engine of their choice.

2021-03-18 17:12 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +The `reduce_dimension*()` process _collapses_ a whole dimension of the datacube. It does so by using some sort of **reducer**, which is a function that calculates a single result from an amount of va
All my grammar suggestions are just from my gut feeling, but having spent two years down under and ingested an English article or two, I'm fairly confident it's correct :)

Yes, "mean value of all timesteps" is perfectly fine too :+1: (I'd keep the "value")

2021-03-18 17:15 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
Yeah that's fine, I prefer "time" in the graphics too.

2021-03-18 17:16 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +In a resampling process, the _layout_ of a certain dimension is changed into another _layout_, most likely also changing the resolution of that dimension. This is done by mapping values of the source
Convinces me :+1: Just leave it then.

2021-03-19 17:13 UTC, jonathom commented on documentation/1.0/datacubes.md
> +It is important to understand that datacubes are designed to make things easier for us, and are not literally a cube, meaning that the above plot is just as good a way to represent the dimensionality
```suggestion
It is important to understand that datacubes are designed to make things easier for us, and are not literally a cube, meaning that the above plot is just as good a representation as any other. That is why we can switch the dimensions around and display them in whatever way we want, including the view below:
```

Yes, perfect. I'll keep your suggested changes in the text and change the figcaption separately.

2021-03-19 17:24 UTC, jonathom commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
```suggestion
A dimension refers to a certain axis of a datacube. Our exemplary raster datacube has the spatial dimensions x and y, and the temporal dimension t. Furthermore it has a bands dimension, extending into the realm of _what kind of information_ is contained in the cube.
```
I agree, how about this? This way it's explicitly about the example cube while not diving too deep. Fixing from "extent" to "axis" as well.
What other dimensions can there be, @m-mohr?

2021-03-19 17:35 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The `reduce_dimension*()` process _collapses_ a whole dimension of the datacube. It does so by using some sort of **reducer**, which is a function that calculates a single result from an amount of va
cool :) will push in next commit.

2021-03-19 17:56 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The resolution of a dimension gives information about what interval lies between observations. This is most obvious with the temporal resolution, where the intervals depict how often obervations were
For example the [sentinel 2 description](https://sentinel.esa.int/web/sentinel/missions/sentinel-2/instrument-payload/resolution-and-swath) states:
> Spectral resolution is defined as a measure of ability to resolve features in the electromagnetic spectrum.

So yep, "how many bands" falls a bit short as an explanation. 
Suggestions are welcome, I'll also try to come up with different wording.

2021-03-19 18:17 UTC, jonathom commented on documentation/1.0/datacubes.md
> +    <figcaption>An example datacube with x, y, bands and time dimension.</figcaption>
I like the 
> "4 dimensions: [list]"

so I added it :)

2021-03-19 18:18 UTC, jonathom commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
great idea! fixing this in a suggestion below this one.

2021-03-19 18:19 UTC, jonathom commented on documentation/1.0/datacubes.md
> +If `n` is larger than 1, the function is called n-ary. In practice, this means that the pixel neighbourhood is taken into account to calculate the new pixel value. Such neighbourhoods can be of tempo
Great idea for the sentence, committing this as well :)

2021-03-19 18:40 UTC, jonathom commented on documentation/1.0/datacubes.md
> +A dimension refers to a certain extent of a datacube. There are the obvious spatial dimensions x and y, and also the temporal dimension t. Furthermore there is the bands dimension, extending into the
Added highlighting.

2021-03-19 19:09 UTC, jonathom commented
I code-highlighted dimension names as well :)

As for the resample-spatial figure:
- Regarding the flat view: To me, displaying the whole cube is important here to communicate that this process is done on the complete thing. That is what I mean when I say, the flat plot wouldn't improve space issue: In the end, the single grids would again be very small, when the complete flat grid is plotted for input and output. 
- "One graphic each for down- and upsampling?" -> yes.
- I prefer making the grids as they are a bit bigger. Because the "resample to" grids are plotted well-visible, I think that would be enough to understand whats happening here. Maybe we can also wait for some community feedback :)

For the temporal resampling: Good points. I will add a timestep then.

And lastly for the reduce-plot: I moved the "time" a bit to the right, will push with the other figure updates.

2021-03-29 00:36 UTC, jonathom commented
Once we have this discussion going (@christophfriedrich), what would you think of including the emoji explanations from the current glossary? Like so:

![Screenshot from 2021-03-29 02-34-38](https://user-images.githubusercontent.com/45635480/112773723-5e9ed280-9037-11eb-82de-d8e89817a6e3.png)
----
![Screenshot from 2021-03-29 02-34-21](https://user-images.githubusercontent.com/45635480/112773724-5f376900-9037-11eb-8bea-51f4ac42d45d.png)


@m-mohr and I initially thought we would leave them out, as to not overload the page & only use one approach on communicating the processes. But the documentation could also benefit from either putting these right below the title or at the very end of every function paragraph. What do you think?

2021-03-29 07:40 UTC, m-mohr commented
We could do it right below the title as an "introduction", something like:

> tl;dr: `filter([🌽, 🥔, 🐔], isVegetarian) => [🌽, 🥔]` ;-)

2021-03-29 08:24 UTC, edzer commented
I'll give it a full read; is https://github.com/Open-EO/openeo.org/blob/datacube_doc/documentation/1.0/datacubes.md still the most up-to-date rendered version?

2021-03-29 08:33 UTC, m-mohr commented
Yes, it's always linking to the latest commit.

2021-03-29 09:10 UTC, christophfriedrich commented
> I code-highlighted dimension names as well :)

Me gusta :+1: 

> Regarding the flat view: To me, displaying the whole cube is important here

Well, the flat view displays the whole cube too?! I'm not sure whether we're talking about the same thing, so I made a sketch. I meant it like this:

![image](https://user-images.githubusercontent.com/17781682/112812898-ea3b5200-907d-11eb-8286-0868ff277106.png)

(For the graphics in the bottom row, I indicated the changes in the top left square only)

IMO removing the perspective helps. But:

> I prefer making the grids as they are a bit bigger.

Looking at the guide right now with the bigger grids I think the point comes across, so I'm not objecting to leaving it as it is :)

> "One graphic each for down- and upsampling?" -> yes.

I think this can stay as it is too.

> For the temporal resampling: Good points. I will add a timestep then.

:+1: 

> And lastly for the reduce-plot: I moved the "time" a bit to the right, will push with the other figure updates.

Looks good now :)

2021-03-29 09:32 UTC, christophfriedrich commented
Regarding the emoji question: I like these explanations -- not only do they explain the concepts once more without the datacube complexity, but they also do so in quite an entertaining way.

I'm unsure about where to put them though. Having a "tl;dr" right below a title doesn't make sense. If we go for this option, calling it "In short" as in your screenshot would be better. But I'd prefer to explain the concept in (a few) words first before the user is confronted with this representation. Putting them at the end seems good because it gives you "a second chance to get it" if you didn't understand the previous stuff 100%. But sitting below the big figures, close to the next section's heading, kind of loses the connection.

Maybe they could be fused into the first few sentences of each section? E.g.:

> When filtering data (e.g. filter_spatial, filter_temporal, filter_bands), only the data that satisfies a condition is returned. In a general example, from a list of ingredients, only some are vegetarian: `filter([🌽, 🥔, 🐔], isVegetarian) => [🌽, 🥔]`. In the EO datacube world, this condition could be a timestamp or interval, (a set of) coordinates, or specific bands. By applying filtering the datacube becomes smaller, according to the selected data.

But that makes a jump totally out of the scope and back in again, so I'm not a complete fan.

Maybe render them as pictures that `float: right` at the top of each section?

I don't have a favourite yet.

---

We could definitely merge first though and worry about this "nice to have addon" later, because in response to @m-mohr's question

> How many issues are still open in this PR? I think we should merge it asap. :-)

I believe there's nothing in here anymore where I'd say "this blocks it for me".

2021-03-29 09:39 UTC, m-mohr commented
Re emojis: Yeah, maybe after the first paragraph when the basics are laid out. I'd keep them in their boxes. I have no strong preference wrt the "heading" we use for it. "In short" might be the best option if put after the first paragraph.

2021-03-29 09:43 UTC, christophfriedrich commented
> Don't render them as images, that is bad for accessibility.

It would help in cross-platform understanding. At least with the font on my machine, I can barely see that this chicken is supposed to be a chicken. And does anyone _really_ benefit from a screenreader reading "filter paranthese bracket ear of corn..."? Also, there's always the `alt` tag.

2021-03-29 09:45 UTC, m-mohr commented
Oh, you meant the single emojis as images? I understood it as "make the whole box an image". I'm still in favor to avoid images, we can also assign a "title" tag to the emojis so that one could hover for better understanding.

2021-03-29 09:49 UTC, christophfriedrich commented
No, I meant rendering the whole expression `filter([🌽, 🥔, 🐔], isVegetarian) => [🌽, 🥔]` as an image. But `title` (on a `<span>`?) for the emojis sounds good too.

2021-03-29 09:51 UTC, christophfriedrich commented
To elaborate more on

> How many issues are still open in this PR?

From my comments, all but 3 have been marked as resolved. Of the remaining three,

- one has a [specific suggestion](https://github.com/Open-EO/openeo.org/pull/31#discussion_r596992414) that could just be merged,
- another [related one](https://github.com/Open-EO/openeo.org/pull/31#discussion_r596030012) can be fixed easily by just including the remaining infos in the table too (or just just click "resolved" without doing anything if you think it's not necessary),
- and for [the last one](https://github.com/Open-EO/openeo.org/pull/31#discussion_r596093481) I'm not sure whether it's actually an issue and if yes how to resolve it, maybe @edzer can help, I'll tag him there too.

2021-03-29 09:52 UTC, christophfriedrich commented on documentation/1.0/datacubes.md
> +The resolution of a dimension gives information about what interval lies between observations. This is most obvious with the temporal resolution, where the intervals depict how often obervations were
@edzer What is your opinion on this?

2021-03-29 10:37 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The resolution of a dimension gives information about what interval lies between observations. This is most obvious with the temporal resolution, where the intervals depict how often obervations were
Maybe "You can also think of how many _and what_ bands you have as the resolution in the `bands` dimension (i.e. spectral resolution)."?

2021-03-29 11:39 UTC, jonathom commented
Thank you for your suggestions, here is what I settled on:
![Screenshot from 2021-03-29 12-57-20](https://user-images.githubusercontent.com/45635480/112830242-8cfdcb80-9092-11eb-91f2-d49c80951f70.png)
All of the code-highlighted example is given the title, because I can't insert html tags inside code-highlighted text, plus I would have wanted a complete textual description anyway. The boxes are inserted after the first paragraph each. Chicken is changed to pig.

Re: the resample figure, I know what you mean. But I'm also happy with it now.

Except for the "spectral resolution" issue there is nothing else, and if nobody objects to the current proposed solution ("how many and what bands") I'm just gonna commit it.

2021-03-29 12:23 UTC, edzer commented on documentation/1.0/datacubes.md
> +The resolution of a dimension gives information about what interval lies between observations. This is most obvious with the temporal resolution, where the intervals depict how often obervations were
I suggest to replace "You can also think of how many bands you have as the resolution in the bands dimension (i.e. spectral resolution)." with "For the `band` dimension, the resolution would correspond to the spectral distance between consecutive bands, but this usually varies from band to band."

2021-03-29 12:40 UTC, edzer commented
Looks great! Besides my comment above on the spectral resolution, I have the following suggestions:

* I think the explanation of `apply*` now only explains `apply_kernel`, and not `apply_dimension`; this can be mentioned, and an example of `apply_dimension` could be added. An example could be: apply_dimension could apply a function to the time dimension that returns the three strongest break points, along with their timing and significance. (or do we need sth simpler?)
*  to the sentence "The resulting grid still carries the same pixel information, but in higher spatial resolution.", add: "Other upsampling methods may yield smoother results, e.g. by using interpolation".
* replace "the dimension along which aggregate is performed" with "the dimension along which the reducer function is applied"

2021-03-29 13:03 UTC, jonathom commented on documentation/1.0/datacubes.md
> +If `n` is larger than 1, the function is called n-ary. In practice, this means that the pixel neighbourhood is taken into account to calculate the new pixel value. Such neighbourhoods can be of tempo
Regarding your first point, I thought that `apply_neighbourhood` is sufficiently explained here via the temporal neighbourhood (with example: smoothing). Then there's also the third `apply` figure where a moving average is applied (introduced with "Of course this also works for temporal neighbourhoods (timeseries), considering neighbours before and after a pixel."). 

Or am I not getting this correctly? We could certainly add the breakpoints example to the brackets: "(e.g. smoothing values over time, breakpoint detection etc.)"

2021-03-29 13:13 UTC, jonathom commented
Thank you for the suggestions @edzer, I just committed points 2 and 3. One extra question: Is it `band` or `bands` dimension?

2021-03-29 13:19 UTC, m-mohr commented
>  One extra question: Is it `band` or `bands` dimension?

bands

2021-03-29 13:24 UTC, jonathom commented on documentation/1.0/datacubes.md
> +The resolution of a dimension gives information about what interval lies between observations. This is most obvious with the temporal resolution, where the intervals depict how often obervations were
committed the above suggestion :)

2021-03-29 19:23 UTC, edzer commented on documentation/1.0/datacubes.md
> +If `n` is larger than 1, the function is called n-ary. In practice, this means that the pixel neighbourhood is taken into account to calculate the new pixel value. Such neighbourhoods can be of tempo
I agree that `apply_neighbourhood` is sufficiently explained, I worried that `apply_dimension` is not sufficiently explained. Breakpoint detection is (in general) _not_ a neighbourhood method.

2021-03-30 09:32 UTC, jonathom commented on documentation/1.0/datacubes.md
> +If `n` is larger than 1, the function is called n-ary. In practice, this means that the pixel neighbourhood is taken into account to calculate the new pixel value. Such neighbourhoods can be of tempo
My mistake. I added an explanation for apply_dimension ([see commit](https://github.com/Open-EO/openeo.org/pull/31/commits/1eabdceff45ec1e30863842a3bea9f5494a8605b)). 
Maybe this is also something that could go in another graphic, as it is important for the difference towards `reduce`. But we can wait for user feedback here.
If you're ok with the new explanation we can push, I think.

2021-03-30 09:35 UTC, m-mohr commented
Thank you @jonathom for all the work you put into it, it is a really good introduction, I think. Thank you for all the reviews.

I'll go ahead and merge this now. We can fine-tune this later via separate PRs, e.g. adding an image for apply_dimension seems to be a good idea.

2021-03-30 09:36 UTC, merged